"""update

Revision ID: 4f2a862cec52
Revises: c0a42ae4c0f3
Create Date: 2024-08-30 13:18:44.934630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2a862cec52'
down_revision = 'c0a42ae4c0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['body'])
    op.create_unique_constraint(None, 'messages', ['username'])
    op.drop_column('messages', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
